name: Production Branch Build

on:
  push:
    branches: [production]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ihua99/test  # Centralized repository name
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Generate Build Metadata
        id: metadata
        run: |
          BUILD_TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          
          echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> $GITHUB_ENV
          echo "RELEASE_TAG=release-$BUILD_TIMESTAMP-$SHORT_SHA" >> $GITHUB_ENV
          echo "::set-output name=tag::$RELEASE_TAG"

      - name: Docker Build and Tag
        run: |
          echo "Building Docker image with tag: ${{ env.RELEASE_TAG }}"
          docker build -t $DOCKER_REPO:${{ env.RELEASE_TAG }} .
          docker tag $DOCKER_REPO:${{ env.RELEASE_TAG }} $DOCKER_REPO:latest
          
          # For debugging
          docker images | grep $DOCKER_REPO

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          echo "Pushing version: ${{ env.RELEASE_TAG }}"
          docker push $DOCKER_REPO:${{ env.RELEASE_TAG }}
          docker push $DOCKER_REPO:latest
          
          # Output the pushed tags for reference
          echo "Successfully pushed tags:"
          echo "- $DOCKER_REPO:${{ env.RELEASE_TAG }}"
          echo "- $DOCKER_REPO:latest"
