name: Production Branch Build

on:
  push:
    branches: [production]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Docker Build and Tag
        id: docker-build
        run: |
          # 使用统一时间戳
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "RELEASE_TAG=release-$TIMESTAMP" >> $GITHUB_ENV
          
          # 构建并标记镜像
          docker build -t ihua99/test:$RELEASE_TAG .
          docker tag ihua99/test:$RELEASE_TAG ihua99/test:latest
          
          # 输出用于后续步骤
          echo "tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push ihua99/test:${{ env.RELEASE_TAG }}
          docker push ihua99/test:latest
